### ISSUE TITLE
Update demo-movies to the latest Meilisearch version

### ISSUE THREAD

**Issue by mdubus** [meilisearch/demo-movies#279]
⚠️ Multilingualism should be anticipated as much as possible to be able to implement easily later

## Script

- [x] Create an account on [https://developers.themoviedb.org/3](https://developers.themoviedb.org/3) and create a token in order to be able to fetch the movies
- [x] Update the script and the packages on [https://github.com/meilisearch/fetch-tv-medias](https://github.com/meilisearch/fetch-tv-medias) to make it compatible with the latest available Meilisearch version (done with https://github.com/meilisearch/fetch-tv-medias/pull/15)
- [x] Use the latest features available (ex: nested fields could now be used instead of transforming the data fetched from TMDB). Read the Meilisearch changelogs to be aware of the new features available
- [x] Remove the `no provider` filter, as we now also want to fetch the movies without providers (could be movies available in the cinema but not yet in streaming) (done with https://github.com/meilisearch/fetch-tv-medias/pull/17)
- [x] Add cast and crew `id` in case we want to make the demo-movies evolve in the future (done with https://github.com/meilisearch/fetch-tv-medias/pull/18)
- [x] Update the GitHub workflow and script to be compatible with the latest Meilisearch version (done with https://github.com/meilisearch/fetch-tv-medias/pull/19)
- [x] Investigate the random crash of the script and fix it (Potentially fixed with https://github.com/meilisearch/fetch-tv-medias/pull/20)
- [x] Update index name after step below (`Meilisearch Instance` is complete) (done with https://github.com/meilisearch/fetch-tv-medias/pull/16)

## Meilisearch instance

- [x] Create a Meilisearch instance with the latest version available (the platform should be discussed with the DevRel team). It could be on the Cloud (beware of the update version feature not available yet), on Digital Ocean, or somewhere else
- [x] Run the script to fetch all the movies (in english) available from the beginning
- [x] Create new index + anticipate the multilingualism (could be of the form `movies-en-US`)
- [x] Import the movies to the new Meilisearch instance
- [x] Create new sets of keys: 
    - One for the GitHub workflow (should be able to add documents)
    - One for the front of the demo movies (search only)
    - One for the landing page (search only)

- [x] Update the settings of the indexes with the following:
```
{
  displayedAttributes: [ '*' ],
  searchableAttributes: [ 'title' ],
  filterableAttributes: [],
  sortableAttributes: [],
  rankingRules: [
    'typo',
    'words',
    'proximity',
    'attribute',
    'exactness',
    'release_date:desc',
    'popularity:desc'
  ],
  stopWords: [],
  synonyms: {},
  distinctAttribute: null
}
```

## Demo movies front

- [x] Update the packages for the meilisearch version used on the Cloud / Digital Ocean (#285)
- [x] Implement the new design when no provider is available (see [design here](https://www.figma.com/file/wUUkpIROZ0r89FxAy3ttLU/Movies-demo?node-id=155%3A146)) (#285)

⚠️ The merge of the script / workflow updates + the update of the Keys (TMDB + Meilisearch instance) should not be done until the new Meilisearch instance is ready, in order to be still able to use the « old » one (used by the landing)

## Once everything is ready

- [x] Merge the script PRs
- [x] Update the keys + index name of the demo-movies front (Vercel)
- [x] Update the keys of the script repository (GitHub repo)
- [x] Update the keys + index name of the landing (GitHub repo + Vercel)
